// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhMwLsEXHuUuE8rcM8AHC5djCAYO-tglA',
    appId: '1:94110626693:web:7642c5256b4b375faa8aec',
    messagingSenderId: '94110626693',
    projectId: 'gamepedia-projek',
    authDomain: 'gamepedia-projek.firebaseapp.com',
    storageBucket: 'gamepedia-projek.firebasestorage.app',
    measurementId: 'G-J63XZCNPGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwYIvhqTScWy8HfnZiinAGr-UBi7tckAI',
    appId: '1:94110626693:android:e6c60d7d42c389d1aa8aec',
    messagingSenderId: '94110626693',
    projectId: 'gamepedia-projek',
    storageBucket: 'gamepedia-projek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1SGKGFA9aQcY6iwxyYPkOqgdcjnxvZic',
    appId: '1:94110626693:ios:5d9acc2ae3a286e4aa8aec',
    messagingSenderId: '94110626693',
    projectId: 'gamepedia-projek',
    storageBucket: 'gamepedia-projek.firebasestorage.app',
    iosBundleId: 'com.example.gamepedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1SGKGFA9aQcY6iwxyYPkOqgdcjnxvZic',
    appId: '1:94110626693:ios:5d9acc2ae3a286e4aa8aec',
    messagingSenderId: '94110626693',
    projectId: 'gamepedia-projek',
    storageBucket: 'gamepedia-projek.firebasestorage.app',
    iosBundleId: 'com.example.gamepedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhMwLsEXHuUuE8rcM8AHC5djCAYO-tglA',
    appId: '1:94110626693:web:960fe11745c608a7aa8aec',
    messagingSenderId: '94110626693',
    projectId: 'gamepedia-projek',
    authDomain: 'gamepedia-projek.firebaseapp.com',
    storageBucket: 'gamepedia-projek.firebasestorage.app',
    measurementId: 'G-0X4SN7DGWB',
  );
}
